# ============================================================================
# Parking Management System - API Package
# ============================================================================

"""
API Package - REST API Entry Points.

This package contains all API route definitions organized by version.
It provides the external interface for the Parking Management System.
"""

# ============================================================================
# API Version 1
# ============================================================================

from src.interfaces.api.v1 import (
    # Main routers
    router as v1_router,
    parking_router,
    vehicle_router,
    charging_router,
    booking_router,
    payment_router,
    notification_router,
    user_router,
    admin_router,
    report_router,
    webhook_router,
    health_router,
    auth_router,
)

# ============================================================================
# API Version 2 (Future)
# ============================================================================

# from src.interfaces.api.v2 import router as v2_router

# ============================================================================
# API Router Factory
# ============================================================================

from fastapi import APIRouter


class APIRouterFactory:
    """
    Factory for creating API routers.
    
    This provides consistent router creation with proper configuration.
    """
    
    @staticmethod
    def create_router(
        prefix: str = "",
        tags: list = None,
        dependencies: list = None,
        responses: dict = None,
    ) -> APIRouter:
        """
        Create a new API router.
        
        Args:
            prefix: Route prefix
            tags: Route tags
            dependencies: Route dependencies
            responses: Route responses
            
        Returns:
            APIRouter: Configured router
        """
        return APIRouter(
            prefix=prefix,
            tags=tags or [],
            dependencies=dependencies or [],
            responses=responses or {},
        )
    
    @staticmethod
    def create_versioned_router(version: str) -> APIRouter:
        """
        Create a versioned API router.
        
        Args:
            version: API version
            
        Returns:
            APIRouter: Versioned router
        """
        return APIRouter(
            prefix=f"/api/{version}",
            tags=[f"API {version.upper()}"],
        )


# ============================================================================
# API Registry
# ============================================================================

class APIRegistry:
    """
    Registry for managing API routers.
    
    This provides a central location for API router registration and discovery.
    """
    
    _routers = {}
    _versioned_routers = {}
    
    @classmethod
    def register(cls, name: str, router: APIRouter):
        """Register a router."""
        cls._routers[name] = router
    
    @classmethod
    def get(cls, name: str) -> Optional[APIRouter]:
        """Get a registered router."""
        return cls._routers.get(name)
    
    @classmethod
    def register_versioned(cls, version: str, router: APIRouter):
        """Register a versioned router."""
        cls._versioned_routers[version] = router
    
    @classmethod
    def get_versioned(cls, version: str) -> Optional[APIRouter]:
        """Get a versioned router."""
        return cls._versioned_routers.get(version)
    
    @classmethod
    def get_all(cls) -> dict:
        """Get all registered routers."""
        return cls._routers.copy()
    
    @classmethod
    def get_all_versioned(cls) -> dict:
        """Get all versioned routers."""
        return cls._versioned_routers.copy()
    
    @classmethod
    def clear(cls):
        """Clear all registered routers."""
        cls._routers.clear()
        cls._versioned_routers.clear()


# ============================================================================
# API Documentation
# ============================================================================

class APIDocumentation:
    """
    API Documentation utilities.
    """
    
    @staticmethod
    def get_openapi_schema():
        """
        Get OpenAPI schema for the API.
        
        Returns:
            dict: OpenAPI schema
        """
        # This would typically be generated by FastAPI's OpenAPI generator
        # This is a placeholder for custom OpenAPI schema generation
        return {
            "openapi": "3.0.0",
            "info": {
                "title": "Parking Management System API",
                "version": "1.0.0",
                "description": "API for the Parking Management System",
                "contact": {
                    "name": "Parking Management Team",
                    "email": "team@parking-system.com",
                },
            },
            "servers": [
                {
                    "url": "https://api.parking-system.com",
                    "description": "Production server",
                },
                {
                    "url": "https://staging-api.parking-system.com",
                    "description": "Staging server",
                },
                {
                    "url": "http://localhost:8000",
                    "description": "Development server",
                },
            ],
            "tags": [
                {"name": "auth", "description": "Authentication endpoints"},
                {"name": "parking", "description": "Parking management endpoints"},
                {"name": "vehicles", "description": "Vehicle management endpoints"},
                {"name": "charging", "description": "EV charging endpoints"},
                {"name": "bookings", "description": "Booking management endpoints"},
                {"name": "payments", "description": "Payment processing endpoints"},
                {"name": "notifications", "description": "Notification endpoints"},
                {"name": "users", "description": "User management endpoints"},
                {"name": "admin", "description": "Administrative endpoints"},
                {"name": "reports", "description": "Reporting endpoints"},
                {"name": "webhooks", "description": "Webhook endpoints"},
                {"name": "health", "description": "Health check endpoints"},
            ],
            "components": {
                "securitySchemes": {
                    "bearerAuth": {
                        "type": "http",
                        "scheme": "bearer",
                        "bearerFormat": "JWT",
                    },
                    "apiKeyAuth": {
                        "type": "apiKey",
                        "in": "header",
                        "name": "X-API-Key",
                    },
                },
                "schemas": {
                    # This would be populated with actual schemas
                },
            },
        }
    
    @staticmethod
    def get_postman_collection():
        """
        Get Postman collection for the API.
        
        Returns:
            dict: Postman collection
        """
        # This would generate a Postman collection for the API
        return {
            "info": {
                "name": "Parking Management System API",
                "description": "API for the Parking Management System",
                "schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json",
            },
            "item": [
                # This would be populated with actual endpoints
            ],
        }


# ============================================================================
# Package Exports
# ============================================================================

__all__ = [
    # Version 1 Routers
    "v1_router",
    "parking_router",
    "vehicle_router",
    "charging_router",
    "booking_router",
    "payment_router",
    "notification_router",
    "user_router",
    "admin_router",
    "report_router",
    "webhook_router",
    "health_router",
    "auth_router",
    
    # Factory
    "APIRouterFactory",
    
    # Registry
    "APIRegistry",
    
    # Documentation
    "APIDocumentation",
]

# ============================================================================
# Version Information
# ============================================================================

__version__ = "1.0.0"
__author__ = "Parking Management Team"